# docker-compose.yml
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: postgres
    ports:exit- "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_db
    ports:
      - "6379:6379"
    restart: unless-stopped

# Em docker-compose.yml
  api:
    build: ./api
    container_name: api_service
    ports:
      - "5000:5000"
    depends_on:
      - redis
    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_service
    ports:
      - "3000:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres_db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: '123456'
      MB_DB_DBNAME: metabase_app
    depends_on:
      - postgres
    restart: unless-stopped

  etl:
    build: ./etl
    container_name: etl_script
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data: