# api/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Comando para iniciar um servidor FastAPI com Uvicorn
# Ele diz: "Use o uvicorn para rodar o objeto 'app' que está dentro do arquivo 'main.py'"
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]